### ISSUE TITLE
Install for execution manager failing on Ubuntu 14.04

### ISSUE THREAD

**Issue by yadudoc** [mturilli/aimes.emanager#1]
I am trying to run this demo on my Ubuntu 14.04 machine, but the install execution manager step, is failing for me with the following error:

```
error: can't copy 'etc/emanager.conf': doesn't exist or not a regular file
    Command "/home/yadu/Virtualenvs/AIMES-DEMO-SC2014/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-4ORJnC/aimes.emanager/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-T9wn7P-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/yadu/Virtualenvs/AIMES-DEMO-SC2014/include/site/python2.7" failed with error code 1 in /tmp/pip-build-4ORJnC/aimes.emanager
```

Complete log from failure is here : http://pastebin.com/YAWjvr1c
I've installed the application and python dependencies listed in the README. Would you have any pointers on what might be going wrong ?

Thanks!

**Comment by mturilli** [comment]
Hi yadudoc,

I have just committed a patch to master for the problem you reported. I tested the installation and it works for me. The problem was setup.py looking for etc/emanager.conf, a file that does not exist anymore. Please let me know whether this solves the problem also for you.

Best,
Matteo

**Comment by yadudoc** [comment]
Hi Matteo,

Works for me now! Thanks.

-Yadu
