### ISSUE TITLE
demo typo

### ISSUE THREAD

**Issue by andre-merzky** [mturilli/aimes.emanager#3]
in section Initialization, I see on the bundle manager command:

```
-u mongodb://54.221.194.147:24242/AIMES-bundle/
```

The env setup has

```
export BUNDLE_DBURL='mongodb://54.221.194.147:24242/AIMES_bundle/'
```

(note `-` vs. `_`)

A related issue is this: assume user_1 runs the demo with a bundle config enabling hopper and stampede, and user_2 _later_ runs the demo with only stampede.  The bundle DB at that point will contain information about hopper, too, and hopper will be eligible for pilot submission, even if user_2 has no account or setup, causing the demo to fail.

One simple solution is to use a private DB url

```
export BUNDLE_DBURL='mongodb://54.221.194.147:24242/AIMES_bundle_<USERNAME>/'
```

and to clear out that private DB before each demo run

```
radical-utils-mongodb.py -m remove -d mongodb://54.221.194.147:24242/AIMES_bundle_<USERNAME>/
```

FWIW, one can also inspect the content of the DB with

```
radical-utils-mongodb.py -m tree -d mongodb://54.221.194.147:24242/AIMES_bundle_<USERNAME>/
radical-utils-mongodb.py -m dump -d mongodb://54.221.194.147:24242/AIMES_bundle_<USERNAME>/
```

I think the pre-populated DB is related to yadu's ticket, but I am not sure that this is the root cause, thus the separate ticket...

**Comment by mturilli** [comment]
Thank you Andre, all very useful. I just committed an updated version of the documentation and of the env_setup.sh script to implement the suggested changes. Please have a look and feel free to close the ticket in case you feel your suggestions have been properly addressed.

**Comment by andre-merzky** [comment]
Diff looks good to me, thanks!  You left an sentence unfinished in the README, around line 150, though :)
