### ISSUE TITLE
user can IDs differ for resources

### ISSUE THREAD

**Issue by andre-merzky** [mturilli/aimes.emanager#4]
Alas, this is the case for me -- I have a different ID on, say, stampede, trestles, india, archer, supermuc.  Very annoying, but not really easy to change.  I can thus use the demo only with one resource at a time, as the script uses a single user ID.

Feel free to not fix this, it might not be worth it for this demo -- but might be good to document explicitly.  Another option is to not specify a userid at all, and to leave that field unset in the contexts -- and instead rely on correct settings in `~/.ssh/config` (which seems to work ok for me).

**Comment by mturilli** [comment]
Hi Andre, 

Thank you for reporting this issue. I have committed a patch and updated the documentation accordingly. Please let me know whether the patches work as expected.

Would you mind to add an example of relevant  `~/.ssh/config` setup to the documentation? In case, I have prepared a placeholder in the README.md with the string `Andre: please insert here your ~/.ssh/config example`.

**Comment by andre-merzky** [comment]
great, thanks!  I added the snippet...
